spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 314369875715-q1jerrfodlsgdutipsm7p957u1k6sags.apps.googleusercontent.com
            client-secret: ZjRR04E5r2_8a5rptAh2jbWI
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect

